version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - restore_cache:
        key: implementation-dataset-{{ .Branch }}
    - run: |
        set -e
        mkdir -p ~/apt-cache/partial
        sudo apt-get -o dir::cache::archives="$HOME"/apt-cache update
        sudo apt-get -o dir::cache::archives="$HOME"/apt-cache install libxml2-utils
    - save_cache:
        key: implementation-dataset-2017-{{ .Branch }}
        paths:
        - ~/apt-cache/partial
    - checkout
    - run: xmllint --noout --schema schema.xsd --xinclude dataset.xml
